# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# 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
name: StatModInsighter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  Run_Stat_Mod_Insights:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pip-${{ hashFiles('**/*.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pandas
        pip install requests
        pip install logging
        pip install python-docx
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: StatModInsights
      env:
        feed_json: "https://raw.githubusercontent.com/ramasureshvijjana/StatModInsights_JSON/master/feed_config.json"
        data_file_path: "https://raw.githubusercontent.com/ramasureshvijjana/StatModInsights_JSON/master/nyc_flights.csv"
      run: |
        python StatModInsighter.py

    - name: Print Working Directory
      run: |
        pwd
        cd /home/runner/work/StatModInsights/StatModInsights
        ls
    - name: Upload Document as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: logs_document
        path: /home/runner/work/StatModInsights/StatModInsights/logs_document.docx

    - name: Download Document Artifact
      uses: actions/download-artifact@v2
      with:
        name: logs_document
        path: /path/on/local/machine